= GR8 CRM - Tags Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM Tags Plugin
:keywords: groovy, grails, crm, gr8crm, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/goeh/grails-crm-tags
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer relationship management
Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

== CRM Tags Plugin

The `crm-tags` plugin provides both storage, service and user interface components for working with tags.


=== Enable tagging support for a domain class
To make a domain class "taggable" you add a static property `taggable` on the class.

[source,groovy]
----
class Person {
  String name

  static taggable = true
}
----

== Services

The `crm-tags` plugin provides a service that you can use to interact with tags and tagged entities.

=== CrmTagService

`CrmTag createTag(Map params)`

Create a new tag.

`void deleteTag(String name, Long tenantId = null)`

Delete an existing tag.

[WARNING]
====
Deleting a tag definition will also delete all occurrences of this tag on domain instances.
====

`void deleteLinks(reference)`

Delete all tags on the domain instance `reference`.

`void setTagValue(def instance, Object[] args)`

Set value of a tag associated with a domain instance.

`def getTagValue(Object instance, String tagName)`

Get the value of a tag associated with a domain instance.

`boolean isTagged(final Object instance, String tagName)`

Check if a domain instance has been tagged with a specific tag.

`Collection deleteTag(Object instance, String tagName)`

Delete a tag associated with a domain instance.

`PagedResultList findAllByTag(Class clazz, Object[] args)`

Find all domain instances with a specific tag.

== Code Examples

Filter domain instances that are tagged with a specific value.

[source,groovy]
----
List<Person> everyone = Person.findAllByTenantId(1L)
List<Person> veryImportantPeople = everyone.findAll{it.isTagged('vip')}
----

The code above is very inefficient because it queries all records from the database then check each one if it got the tag.
In this case it's better to use the domain class method `findAllByTag` because it uses a more efficient SQL query.

[source,groovy]
----
List<Person> veryImportantPeople = Person.findAllByTag('vip')
----

NOTE: findAllByTag() automatically applies a *tenant filter* to the query, so the query above will only find people in the current executing tenant.

== Changes

2.4.3:: Pre-defined tags are now rendered as checkboxes in edit mode and with green (success) color in display mode
2.4.2:: Tag values are now deleted when the owning domain instance is deleted
2.4.1:: The method `domainInstance.isTagged(String)` is now case insensitive
2.4.0:: First version compatible with Grails 2.4.4.
2.0.0:: First public release.

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.